
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-4pm-7
owner: ucsb-cs156-s24
repo_name: team01-s24-4pm-7
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"Che-Tides","number":20,"title":"Creating TidesQueryService and TidesQueryServiceTests","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-7/pull/20"},{"author":{"id":"U_kgDOBYEQGw","is_bot":false,"login":"nadavital","name":"Nadav Avital"},"headRefName":"Nadav-Joke","number":18,"title":"Nadav joke","url":"https://github.com/ucsb-cs156-s24/team01-s24-4pm-7/pull/18"}]
